theme: jekyll-theme-slate
title: Online News Sites as Disruptive Technology
description: This is a webpage which discusses  how the online distribution of news through online sites, with additional mention to social media, is now a new and common means for how publishers disseminate information to the public, and how these people receive them. We iterate online news sites as one of the many examples of disruptive technology but first and foremost: What is Disruptive Technology?
show_downloads: False
navigation:
  - title: Home
    url: /
