theme: jekyll-theme-slate
title: Disruptive Technologies
description: The disruptive innovators of 10 years ago are today’s stable incumbents.
url: "https://punzalanmoira.github.io/mms142-groupL-2020.github.io/"
markdown: GFM
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: About Us
    url: about
    
